# .travis.yml
cache: yarn
before_install:
  - git fetch --unshallow
  - yarn global add vsce
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - /bin/bash scripts/lint-commits.sh
after_script: greenkeeper-lockfile-upload
stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false
  - name: integrate
    if: branch =~ /^greenkeeper-.*$/ AND type = pull_request AND fork = false
jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      script: yarn semantic-release
    - stage: integrate
      language: node_js
      node_js: '8'
      script: yarn package
notifications:
  email: false
